program BM;

uses
  Vcl.Forms,
  View.MainForm in 'Views\View.MainForm.pas' {MainForm},
  Model.Base in 'Models\Model.Base.pas',
  Model.IMyConnection in 'Models\Model.IMyConnection.pas',
  View.EmployeeListForm in 'Views\View.EmployeeListForm.pas' {EmployeeListForm},
  View.TahakkukForm in 'Views\View.TahakkukForm.pas' {TahakkukForm},
  Model.ProSu.InterfaceActions in 'SupportCode\Model.ProSu.InterfaceActions.pas',
  Model.ProSu.Interfaces in 'SupportCode\Model.ProSu.Interfaces.pas',
  Model.ProSu.Provider in 'SupportCode\Model.ProSu.Provider.pas',
  Model.ProSu.Subscriber in 'SupportCode\Model.ProSu.Subscriber.pas',
  Model.Interfaces in 'Models\Model.Interfaces.pas',
  Model.Main in 'Models\Model.Main.pas',
  Model.Declarations in 'Models\Model.Declarations.pas',
  ViewModel.Main in 'ViewModels\ViewModel.Main.pas',
  View.TemplateForm in 'Views\View.TemplateForm.pas' {TemplateForm},
  ViewModel.CountryList in 'ViewModels\ViewModel.CountryList.pas',
  Model.Country in 'Models\Model.Country.pas',
  Model.FormDeclarations in 'Models\Model.FormDeclarations.pas',
  View.TemplateEdit in 'Views\Edits\View.TemplateEdit.pas' {TemplateEdit},
  Model.Fabrication in 'SupportCode\Model.Fabrication.pas',
  Model.LanguageDictionary in 'Models\Model.LanguageDictionary.pas',
  MainDM in 'MainDM.pas' {DMMain: TDataModule},
  Model.Employee in 'Models\Model.Employee.pas',
  ViewModel.EmployeeList in 'ViewModels\ViewModel.EmployeeList.pas',
  ViewModel.CountryEdit in 'ViewModels\Edits\ViewModel.CountryEdit.pas',
  Model.SQLiteConnection in 'Models\Model.SQLiteConnection.pas',
  View.CountryEdit in 'Views\Edits\View.CountryEdit.pas' {CountryEditForm},
  Model.Company in 'Models\Model.Company.pas',
  ViewModel.CompanyList in 'ViewModels\ViewModel.CompanyList.pas',
  View.CompanyListForm in 'Views\View.CompanyListForm.pas' {CompanyListForm},
  Model.MosObjectDataset in 'Models\Model.MosObjectDataset.pas',
  View.CompanyEdit in 'Views\Edits\View.CompanyEdit.pas' {CompanyEditForm},
  View.EmployeeEdit in 'Views\Edits\View.EmployeeEdit.pas' {EmployeeEditForm},
  View.TitleListForm in 'Views\View.TitleListForm.pas' {TitleListForm},
  Model.Title in 'Models\Model.Title.pas',
  ViewModel.TitleList in 'ViewModels\ViewModel.TitleList.pas',
  View.TemplateSelectForm in 'Views\Selects\View.TemplateSelectForm.pas' {TemplateSelectForm},
  View.CompanySelectForm in 'Views\Selects\View.CompanySelectForm.pas' {CompanySelectForm},
  View.CityListForm in 'Views\View.CityListForm.pas' {CityListForm},
  View.CityEdit in 'Views\Edits\View.CityEdit.pas' {CityEditForm},
  Model.City in 'Models\Model.City.pas',
  ViewModel.CityList in 'ViewModels\ViewModel.CityList.pas',
  Model.TownCityCountryTree in 'Models\Model.TownCityCountryTree.pas',
  Model.FileUpload in 'Models\Model.FileUpload.pas',
  ViewModel.TitleEdit in 'ViewModels\Edits\ViewModel.TitleEdit.pas',
  View.TitleEdit in 'Views\Edits\View.TitleEdit.pas' {TitleEditForm},
  ViewModel.EmployeeEdit in 'ViewModels\Edits\ViewModel.EmployeeEdit.pas',
  ViewModel.CompanyEdit in 'ViewModels\Edits\ViewModel.CompanyEdit.pas',
  View.PictureForm in 'Views\View.PictureForm.pas' {PictureForm},
  View.TownListForm in 'Views\View.TownListForm.pas' {TownListForm},
  Model.Town in 'Models\Model.Town.pas',
  ViewModel.TownList in 'ViewModels\ViewModel.TownList.pas',
  View.TownEdit in 'Views\Edits\View.TownEdit.pas' {TownEditForm},
  Model.CityCountryTree in 'Models\Model.CityCountryTree.pas',
  Model.Currency in 'Models\Model.Currency.pas',
  ViewModel.CurrencyList in 'ViewModels\ViewModel.CurrencyList.pas',
  View.CurrencyListForm in 'Views\View.CurrencyListForm.pas' {CurrencyListForm},
  View.CurrencyEdit in 'Views\Edits\View.CurrencyEdit.pas' {CurrencyEditForm},
  Sec.Declarations in 'Security\Sec.Declarations.pas',
  View.LoginForm in 'Views\View.LoginForm.pas' {LoginForm},
  Support.IdentityVerification in 'SupportCode\Support.IdentityVerification.pas',
  Model.PermissionList in 'SupportCode\Model.PermissionList.pas',
  View.CountryListForm in 'Views\View.CountryListForm.pas' {CountryListForm},
  View.PermissionListForm in 'Views\View.PermissionListForm.pas' {PermissionListForm},
  Model.Permission in 'Models\Model.Permission.pas',
  ViewModel.PermissionList in 'ViewModels\ViewModel.PermissionList.pas',
  Model.Consts in 'Models\Model.Consts.pas',
  View.PermissionEdit in 'Views\Edits\View.PermissionEdit.pas' {PermissionEditForm},
  View.LocationListForm in 'Views\View.LocationListForm.pas' {LocationListForm},
  Model.Location in 'Models\Model.Location.pas',
  ViewModel.LocationList in 'ViewModels\ViewModel.LocationList.pas',
  View.LocationEdit in 'Views\Edits\View.LocationEdit.pas' {LocationEditForm},
  Model.RelationshipType in 'Models\Model.RelationshipType.pas',
  ViewModel.RelationshipType in 'ViewModels\ViewModel.RelationshipType.pas',
  View.RelationshipTypeListForm in 'Views\View.RelationshipTypeListForm.pas' {RelationshipTypeListForm},
  View.RelationshipTypeEdit in 'Views\Edits\View.RelationshipTypeEdit.pas' {RelationshipTypeEditForm},
  Model.Department in 'Models\Model.Department.pas',
  ViewModel.DepartmentList in 'ViewModels\ViewModel.DepartmentList.pas',
  View.DepartmentListForm in 'Views\View.DepartmentListForm.pas' {DepartmentListForm},
  View.DepartmentEdit in 'Views\Edits\View.DepartmentEdit.pas' {DepartmentEditForm},
  View.OthIncomeOutcomeDefListForm in 'Views\View.OthIncomeOutcomeDefListForm.pas' {OthIncomeOutcomeDefListForm},
  View.OthIncomeOutcomeDefEdit in 'Views\Edits\View.OthIncomeOutcomeDefEdit.pas' {OthIncomeOutcomeDefEditForm},
  Model.OthIncomeOutcomeDef in 'Models\Model.OthIncomeOutcomeDef.pas',
  ViewModel.OthIncomeOutcomeDefList in 'ViewModels\ViewModel.OthIncomeOutcomeDefList.pas',
  Model.User in 'Models\Model.User.pas',
  ViewModel.UserList in 'ViewModels\ViewModel.UserList.pas',
  View.UserListForm in 'Views\View.UserListForm.pas' {UserListForm},
  View.UserEdit in 'Views\Edits\View.UserEdit.pas' {UserEditForm},
  Model.Group in 'Models\Model.Group.pas',
  ViewModel.GroupList in 'ViewModels\ViewModel.GroupList.pas',
  View.GroupListForm in 'Views\View.GroupListForm.pas' {GroupListForm},
  View.GroupEdit in 'Views\Edits\View.GroupEdit.pas' {GroupEditForm},
  Model.GroupUser in 'Models\Model.GroupUser.pas',
  Model.RoleUserGroupPermission in 'Models\Model.RoleUserGroupPermission.pas',
  Model.RoleUserGroup in 'Models\Model.RoleUserGroup.pas',
  View.RoleListForm in 'Views\View.RoleListForm.pas' {RoleListForm},
  Model.Role in 'Models\Model.Role.pas',
  ViewModel.RoleList in 'ViewModels\ViewModel.RoleList.pas',
  View.RoleEdit in 'Views\Edits\View.RoleEdit.pas' {RoleEditForm},
  View.OthIncomeOutcomeListForm in 'Views\View.OthIncomeOutcomeListForm.pas' {OthIncomeOutcomeListForm},
  View.OthIncomeOutcomeEdit in 'Views\Edits\View.OthIncomeOutcomeEdit.pas' {OthIncomeOutcomeEditForm};

{$R *.res}

begin
  Application.Initialize;
  Application.ShowHint := True;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
