unit Model.Declarations;

interface
uses
  Spring.Persistence.Mapping.Attributes,
  Spring,
  Model.Base,
  System.Classes,
  Model.LanguageDictionary;

type

  NullInteger = Nullable<Int64>;
  NullString = Nullable<String>;
  NullExtended = Nullable<Extended>;
  NullBool = Nullable<Boolean>;
  NullDate = Nullable<TDate>;
  NullDateTime = Nullable<TDateTime>;
  NullTime = Nullable<TTime>;

  TGenders = (Male = 1, Female = 2, Other = 3);

  TMaritalStatus = (Single = 1, Married = 2, Divorced = 3, Widow = 4);

  TWagePeriods = (Hourly = 1, Daily = 2, Weekly = 3, Monthly = 4);

  TComputationType = (Amount = 0, Percentage = 1, ComputeWithScript = 2);

var
  GendersStr : Array[TGenders] of string = ('Male', 'Female', 'Other');
  MaritalStatusStr : Array[TMaritalStatus] of string = ('Single', 'Married', 'Divorced', 'Widow');
  WagePeriodsStr : Array[TWagePeriods] of string = ('Hourly', 'Daily', 'Weekly', 'Monthly');
  ComputationTypeStr : Array[TComputationType] of string = ('Amount', 'Percentage', 'Compute with script');

type

  [Entity]
  [Table('Currency')]
  TCurrency = class(TBaseModel)
  private
    FCurrencyId : Integer;
    FCurrencyCode : NullString;
    FCurrencyName : NullString;
    FSortOrder : NullInteger;
    FMultiplier : NullInteger;
    FPrecisionNumber : NullInteger;
    FRefId : NullInteger;
  published
    [Column('CurrencyId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property CurrencyId: Integer read FCurrencyId write FCurrencyId;
    [Column([cpRequired, cpNotNull], 5, 0, 0)]
    property CurrencyCode: NullString read FCurrencyCode write FCurrencyCode;
    [Column([], 50, 0, 0)]
    property CurrencyName: NullString read FCurrencyName write FCurrencyName;
    [Column]
    property SortOrder : NullInteger read FSortOrder write FSortOrder;
    [Column]
    property Multiplier: NullInteger read FMultiplier write FMultiplier;
    [Column]
    property PrecisionNumber: NullInteger read FPrecisionNumber write FPrecisionNumber;
    [Column]
    property RefId: NullInteger read FRefId write FRefId;
  end;

  [Entity]
  [Table('CurrencyDaily')]
  TCurrencyDaily = class(TBaseModel)
  private
    [Column('CurrencyDailyId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    FCurrencyDailyId : Integer;
    FCurrencyId : NullInteger;
    FMarketBuyValue : NullExtended;
    FMarketSalesValue : NullExtended;
    FFormalBuyValue : NullExtended;
    FFormalSalesValue : NullExtended;
    FFormalEffectiveBuyValue : NullExtended;
    FFormalEffectiveSalesValue : NullExtended;
    FMarketSaleValue: NullExtended;
  published
    property CurrencyDailyId: Integer read FCurrencyDailyId write FCurrencyDailyId;
    [Column]
    [ForeignJoinColumn('CurrencyId', 'Currency', 'CurrencyId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    property CurrencyId: NullInteger read FCurrencyId write FCurrencyId;
    [Column]
    property MarketBuyValue: NullExtended read FMarketBuyValue write FMarketBuyValue;
    [Column]
    property MarketSalesValue: NullExtended read FMarketSaleValue write FMarketSaleValue;
    [Column]
    property FormalBuyValue: NullExtended read FFormalBuyValue write FFormalBuyValue;
    [Column]
    property FormalSalesValue: NullExtended read FFormalSalesValue write FFormalSalesValue;
    [Column]
    property FormalEffectiveBuyValue: NullExtended read FFormalEffectiveBuyValue write FFormalEffectiveBuyValue;
    [Column]
    property FormalEffectiveSalesValue: NullExtended read FFormalEffectiveSalesValue write FFormalEffectiveSalesValue;
  end;

  [Entity]
  [Table('Country')]
  TCountry = class(TBaseModel)
  private
    FCountryId : Integer;
    FCountryName : NullString;
    FCode3 : NullString;
    FCode2 : NullString;
  published
    [Column('CountryId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property CountryId: Integer read FCountryId write FCountryId;
    [Column([], 50, 0, 0)]
    property CountryName: NullString read FCountryName write FCountryName;
    [Column([], 3, 0, 0)]
    property Code3: NullString read FCode3 write FCode3;
    [Column([], 2, 0, 0)]
    property Code2: NullString read FCode2 write FCode2;
  end;

  [Entity]
  [Table('Language')]
  TLanguage = class(TBaseModel)
  private
    FLanguageId : Integer;
    FLanguageName : NullString;
  published
    [Column('LanguageId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property LanguageId: Integer read FLanguageId write FLanguageId;
    [Column([], 50, 0, 0)]
    property LanguageName: NullString read FLanguageName write FLanguageName;
  end;

  [Entity]
  [Table('Company')]
  TCompany = class(TBaseModel)
  private
    FCompanyId : Integer;
    FCompanyCode : NullString;
    FCompanyGuid : NullString;
    FDocPassword : NullString;
    FCompanyName1 : NullString;
    FCompanyName2 : NullString;
    FCompanyAddress1 : NullString;
    FCompanyAddress2 : NullString;
    FCompanyAddress3 : NullString;
    FStreet : NullString;
    FTownId : NullInteger;
    FShortName : NullString;
    FTaxOffice : NullString;
    FTaxRegistrationNumber : NullString;
    FLogoImage32x32 : NullString;
    FLogoImage256x256 : NullString;
    FLogoImageBig : NullString;
    FPostCode : NullString;
    FPhone1 : NullString;
    FPhone2 : NullString;
    FFax : NullString;
    FEmployeeName1 : NullString;
    FEmployeeName2 : NullString;
    FResponsible1 : NullString;
    FResponsible2 : NullString;
    FCurrentYear : NullInteger;
    FCurrentPeriod : NullInteger;
  published
    [Column('CompanyId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property CompanyId: Integer read FCompanyId write FCompanyId;
    [Column([], 20, 0, 0)]
    property CompanyCode: NullString read FCompanyCode write FCompanyCode;
    [Column([], 50, 0, 0)]
    property CompanyGuid: NullString read FCompanyGuid write FCompanyGuid;
    [Column([], 500, 0, 0)]
    property DocPassword: NullString read FDocPassword write FDocPassword;
    [Column([], 50, 0, 0)]
    property CompanyName1: NullString read FCompanyName1 write FCompanyName1;
    [Column([], 50, 0, 0)]
    property CompanyName2: NullString read FCompanyName2 write FCompanyName2;
    [Column([], 50, 0, 0)]
    property CompanyAddress1: NullString read FCompanyAddress1 write FCompanyAddress1;
    [Column([], 50, 0, 0)]
    property CompanyAddress2: NullString read FCompanyAddress2 write FCompanyAddress2;
    [Column([], 50, 0, 0)]
    property CompanyAddress3: NullString read FCompanyAddress3 write FCompanyAddress3;
    [Column([], 50, 0, 0)]
    property Street: NullString read FStreet write FStreet;
    [Column]
    property TownId: NullInteger read FTownId write FTownId;
    [Column([], 10, 0, 0)]
    property ShortName: NullString read FShortName write FShortName;
    [Column([], 50, 0, 0)]
    property TaxOffice: NullString read FTaxOffice write FTaxOffice;
    [Column([], 20, 0, 0)]
    property TaxRegistrationNumber: NullString read FTaxRegistrationNumber write FTaxRegistrationNumber;
    [Column([], 120, 0, 0)]
    property LogoImage32x32: NullString read FLogoImage32x32 write FLogoImage32x32;
    [Column([], 120, 0, 0)]
    property LogoImage256x256: NullString read FLogoImage256x256 write FLogoImage256x256;
    [Column([], 120, 0, 0)]
    property LogoImageBig: NullString read FLogoImageBig write FLogoImageBig;
    [Column([], 20, 0, 0)]
    property PostCode: NullString read FPostCode write FPostCode;
    [Column([], 20, 0, 0)]
    property Phone1: NullString read FPhone1 write FPhone1;
    [Column([], 20, 0, 0)]
    property Phone2: NullString read FPhone2 write FPhone2;
    [Column([], 20, 0, 0)]
    property Fax: NullString read FFax write FFax;
    [Column([], 50, 0, 0)]
    property EmployeeName1: NullString read FEmployeeName1 write FEmployeeName1;
    [Column([], 50, 0, 0)]
    property EmployeeName2: NullString read FEmployeeName2 write FEmployeeName2;
    [Column([], 50, 0, 0)]
    property Responsible1: NullString read FResponsible1 write FResponsible1;
    [Column([], 50, 0, 0)]
    property Responsible2: NullString read FResponsible2 write FResponsible2;
    [Column]
    property CurrentYear: NullInteger read FCurrentYear write FCurrentYear;
    [Column]
    property CurrentPeriod: NullInteger read FCurrentPeriod write FCurrentPeriod;
  end;

  [Entity]
  [Table('City')]
  TCity = class(TBaseModel)
  private
    FCityId: Integer;
    FCountryId: NullInteger;
    FCityName: NullString;
    FCityCode: NullString;
    function GetCountryName : string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CountryId')]
    FCountry : TCountry;
  published
    [Column('CityId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [Id]
    [AutoGenerated]
    property CityId: Integer read FCityId write FCityId;
    [Column]
    [ForeignJoinColumn('CountryId', 'Country', 'CountryId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CountryId: NullInteger read FCountryId write FCountryId;
    [Column([], 50, 0, 0)]
    property CityName: NullString read FCityName write FCityName;
    [Column([], 50, 0, 0)]
    property CityCode: NullString read FCityCode write FCityCode;
    property Country: string read GetCountryName;
  end;

  [Entity]
  [Table('Town')]
  TTown = class(TBaseModel)
  private
    FTownId: Integer;
    FCityId: NullInteger;
    FTownName: NullString;
    function GetCity: string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CityId')]
    FCity : TCity;
  published
    [Column('TownId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property TownId: Integer read FTownId write FTownId;
    [ForeignJoinColumn('CityId', 'City', 'CityId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    [Column]
    property CityId: NullInteger read FCityId write FCityId;
    [Column([], 50, 0, 0)]
    property TownName: NullString read FTownName write FTownName;
    property City: string read GetCity;
  end;

  [Entity]
  [Table('Location')]
  TLocation = class(TBaseModel)
  private
    FLocationId: Integer;
    FLocationCode: NullString;
    FLocationName: NullString;
    FCompanyId: Integer;
    FLocationAddress1: NullString;
    FStreet: NullString;
    FLocationAddress2: NullString;
    FLocationAddress3: NullString;
    FRegion: NullString;
    FTownId: NullInteger;
    FPostCode: NullString;
    FPhone1: NullString;
    FFax: NullString;
    FPhone2: NullString;
    FTaxOffice: NullString;
    FTaxRegistrationNumber: NullString;
    FEmployeeName1: NullString;
    FEmployeeName2: NullString;
    FResponsible1: NullString;
    FResponsible2: NullString;
    FLatitude: NullExtended;
    FLongtitude: NullExtended;
    function GetTown: string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'TownId')]
    FTown : TTown;
  published
    [Column('LocationId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property LocationId: Integer read FLocationId write FLocationId;
    [Column([], 10, 0, 0)]
    property LocationCode: NullString read FLocationCode write FLocationCode;
    [Column([], 50, 0, 0)]
    property LocationName: NullString read FLocationName write FLocationName;
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    [Column]
    property CompanyId: Integer read FCompanyId write FCompanyId;
    [Column([], 50, 0, 0)]
    property LocationAddress1: NullString read FLocationAddress1 write FLocationAddress1;
    [Column([], 50, 0, 0)]
    property LocationAddress2: NullString read FLocationAddress2 write FLocationAddress2;
    [Column([], 50, 0, 0)]
    property LocationAddress3: NullString read FLocationAddress3 write FLocationAddress3;
    [Column([], 50, 0, 0)]
    property Street: NullString read FStreet write FStreet;
    [Column([], 50, 0, 0)]
    property Region: NullString read FRegion write FRegion;
    [Column]
    [ForeignJoinColumn('TownId', 'Town', 'TownId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property TownId: NullInteger read FTownId write FTownId;
    [Column([], 20, 0, 0)]
    property PostCode: NullString read FPostCode write FPostCode;
    [Column([], 20, 0, 0)]
    property Phone1: NullString read FPhone1 write FPhone1;
    [Column([], 20, 0, 0)]
    property Phone2: NullString read FPhone2 write FPhone2;
    [Column([], 20, 0, 0)]
    property Fax: NullString read FFax write FFax;
    [Column([], 50, 0, 0)]
    property TaxOffice: NullString read FTaxOffice write FTaxOffice;
    [Column([], 20, 0, 0)]
    property TaxRegistrationNumber: NullString read FTaxRegistrationNumber write FTaxRegistrationNumber;
    [Column([], 50, 0, 0)]
    property EmployeeName1: NullString read FEmployeeName1 write FEmployeeName1;
    [Column([], 50, 0, 0)]
    property EmployeeName2: NullString read FEmployeeName2 write FEmployeeName2;
    [Column([], 50, 0, 0)]
    property Responsible1: NullString read FResponsible1 write FResponsible1;
    [Column([], 50, 0, 0)]
    property Responsible2: NullString read FResponsible2 write FResponsible2;
    [Column]
    property Latitude: NullExtended read FLatitude write FLatitude;
    [Column]
    property Longtitude: NullExtended read FLongtitude write FLongtitude;
    property Town: string read GetTown;
  end;

{  [Entity]
  [Table('CompanyLocation')]
  TCompanyLocation = class(TBaseModel)
  private
    FCompanyLocationId: Integer;
    FLocationId: NullInteger;
    FCompanyId: NullInteger;
    FHeadquarter: NullBool;
    function GetLocationName: string;
    function GetLocationCode: string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'LocationId')]
    FLocation : TLocation;
  published
    [Column('CompanyLocationId', [cpRequired, cpPrimaryKey, cpNotNull], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property CompanyLocationId: Integer read FCompanyLocationId write FCompanyLocationId;
    [ForeignJoinColumn('LocationId', 'Location', 'LocationId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    [Column]
    property LocationId: NullInteger read FLocationId write FLocationId;
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    [Column]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column]
    property Headquarter: NullBool read FHeadquarter write FHeadquarter;
    property LocationName: string read GetLocationName;
    property LocationCode: string read GetLocationCode;
  end;
}
  [Entity]
  [Table('[Permission]')]
  TPermission = class(TBaseModel)
  private
    FPermissionId : Integer;
    FPermissionName : NullString;
    FParentId : NullInteger;
    FModulClassName: string;
  published
    [Column('PermissionId', [cpRequired, cpPrimaryKey, cpNotNull], 0, 0, 0, 'Primary Key')]
    //[AutoGenerated]
    [Id]
    property PermissionId : Integer read FPermissionId write FPermissionId;
    [Column('PermissionName', [], 100, 0, 0)]
    property PermissionName : NullString read FPermissionName write FPermissionName;
    [Column]
    property ParentId : NullInteger read FParentId write FParentId;
    [Column([], 100, 0, 0)]
    property ModulClassName: string read FModulClassName write FModulClassName;
  end;

  [Entity]
  [Table('[User]')]
  TUser = class(TBaseModel)
  private
    FUserId : Integer;
    FUserName : NullString;
    FPassword : NullString;
    FUserGuid : NullString;
    FDocPassword : NullString;

    FCompanyId : NullInteger;
    FLocationId : NullInteger;
    FMobilePhone : NullString;
    FSmsAvailable : NullBool;
    FMobilePhoneVerified : NullBool;

    FEmail : NullString;
    FEmailAvailable : NullBool;
    FEMailVerified : NullBool;

    function GetCompanyCode: string;
    function GetCompanyName: string;
    function GetLocationCode: string;
    function GetLocationName: string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CompanyId')]
    FCompany : TCompany;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'LocationId')]
    FLocation : TLocation;
  published
    [Column('UserId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    [Id]
    property UserId : Integer read FUserId write FUserId;
    [Column([], 50, 0, 0)]
    property UserName : NullString read FUserName write FUserName;
    [Column([], 100, 0, 0)]
    property Password : NullString read FPassword write FPassword;
    [Column([], 50, 0, 0)]
    property UserGuid : NullString read FUserGuid write FUserGuid;
    [Column([], 100, 0, 0)]
    property DocPassword : NullString read FDocPassword write FDocPassword;

    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    [Column]
    property CompanyId : NullInteger read FCompanyId write FCompanyId;
    [Column]
    property LocationId : NullInteger read FLocationId write FLocationId;
    [Column([], 20, 0, 0)]
    property MobilePhone : NullString read FMobilePhone write FMobilePhone;
    [Column]
    property SmsAvailable : NullBool read FSmsAvailable write FSmsAvailable;
    [Column]
    property MobilePhoneVerified : NullBool read FMobilePhoneVerified write FMobilePhoneVerified;
    [Column([], 100, 0, 0)]
    property EMail : NullString read FEMail write FEMail;
    [Column]
    property EmailAvailable : NullBool read FEmailAvailable write FEmailAvailable;
    [Column]
    property EMailVerified : NullBool read FEMailVerified write FEMailVerified;

    property CompanyName: string read GetCompanyName;
    property CompanyCode: string read GetCompanyCode;
    property LocationName: string read GetLocationName;
    property LocationCode: string read GetLocationCode;
  end;

  [Entity]
  [Table('[Role]')]
  TRole = class(TBaseModel)
  Private
    FRoleId : Integer;
    FCompanyId : NullInteger;
    FRoleName : NullString;
    function GetCompanyCode: string;
    function GetCompanyName: string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CompanyId')]
    FCompany : TCompany;
  published
    [Column('RoleId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property RoleId : Integer read FRoleId write FRoleId;
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    [Column]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column([], 50, 0, 0)]
    property RoleName : NullString read FRoleName write FRoleName;
    property CompanyName: string read GetCompanyName;
    property CompanyCode: string read GetCompanyCode;
  end;

  [Entity]
  [Table('[Group]')]
  TGroup = class(TBaseModel)
  private
    FGroupId : Integer;
    FCompanyId : NullInteger;
    FGroupName : NullString;
    FParentId : NullInteger;
  published
    [Column('GroupId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    property GroupId: Integer read FGroupId write FGroupId;
    [Column]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column([], 50, 0, 0)]
    property GroupName: NullString read FGroupName write FGroupName;
    [Column]
    property ParentId: NullInteger read FParentId write FParentId;
  end;


  [Entity]
  [Table('GroupUser')]
  TGroupUser = class(TBaseModel)
  private
    FGroupUserId : Integer;
    FGroupId : NullInteger;
    FUserId : NullInteger;
    FGroupManager : NullBool;
  {public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'GroupId')]
    FGroup : TGroup;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'UserId')]
    FUser : TUser;}
  published
    [Column('GroupUserId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [Id]
    property GroupUserId: Integer read FGroupUserId write FGroupUserId;
    [ForeignJoinColumn('GroupId', '[Group]', 'GroupId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    [Column]
    property GroupId: NullInteger read FGroupId write FGroupId;
    //[ForeignJoinColumn('UserId', '[User]', 'UserId', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    [Column]
    property UserId: NullInteger read FUserId write FUserId;
    [Column]
    property GroupManager: NullBool read FGroupManager write FGroupManager;
  end;

  TGroupUserExt = class(TGroupUser)
  private
    {[ManyToOneAttribute(false, [ckCascadeMerge], 'GroupId')]
    FGroup : TGroup;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'UserId')]
    FUser : TUser;}
    FUsername : string;
    FGroupName : string;
    function GetGroupName: string;
    procedure SetGroupName(const Value : string);
    function GetUsername: string;
    procedure SetUserName(const Value : string);
  public
    {[ManyToOneAttribute(True, [ckCascadeMerge], 'UserId')]
    property User : TUser read FUser write FUser;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'GroupId')]
    property Group : TGroup read FGroup write FGroup;}
  published
    property GroupName: string read GetGroupName write SetGroupName;
    property Username: string read GetUsername write SetUserName;
  end;

  ///
  //  Bu tablo User ya da Group'a verilen rolleri içermektedir.
  //
  [Entity]
  [Table('RoleUserGroup')]
  TRoleUserGroup = class(TBaseModel)
  private
    FUserGroupRoleId : Integer;
    FUserId : NullInteger;
    FGroupId : NullInteger;
    FRoleId : NullInteger;
    FIsUser : NullBool;
  published
    [Column('RoleUserGroupId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    property UserGroupRoleId: Integer read FUserGroupRoleId write FUserGroupRoleId;
    [ForeignJoinColumn('UserId', '[User]', 'UserId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    [Column]
    property UserId: NullInteger read FUserId write FUserId;
    [ForeignJoinColumn('GroupId', '[Group]', 'GroupId', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    [Column]
    property GroupId: NullInteger read FGroupId write FGroupId;
    [Column]
    [ForeignJoinColumn('RoleId', '[Role]', 'RoleId', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    property RoleId: NullInteger read FRoleId write FRoleId;
    [Column]
    property IsUser: NullBool read FIsUser write FIsUser;
  end;

  TRoleUserGroupExt = class(TRoleUserGroup)
  private
    FUsername: string;
    FGroupName: string;
    FRoleName: string;
  public
    {[ManyToOneAttribute(false, [ckCascadeMerge], 'UserId')]
    property User : TUser read FUser write FUser;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'GroupId')]
    property Group : TGroup read FGroup write FGroup;}
  published
    property GroupName: string read FGroupName write FGroupName;
    property RoleName: string read FRoleName write FRoleName;
    property Username: string read FUsername write FUsername;
  end;


  [Entity]
  [Table('RoleUserGroupPermission')]
  TRoleUserGroupPermission = class(TBaseModel)
  private
    FRUGPermissionId : Integer;
    FRoleId : NullInteger;
    FUserId : NullInteger;
    FGroupId : NullInteger;
    FPermissionId : NullInteger;
    FRUG : NullInteger;
  published
    [Column('RUGPermissionId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    property RUGPermissionId: Integer read FRUGPermissionId write FRUGPermissionId;

    [ForeignJoinColumn('RoleId', '[Role]', 'RoleId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    [Column]
    property RoleId: NullInteger read FRoleId write FRoleId;

    [ForeignJoinColumn('UserId', '[User]', 'UserId', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    [Column]
    property UserId: NullInteger read FUserId write FUserId;
    [ForeignJoinColumn('GroupId', '[Group]', 'GroupId', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    [Column]
    property GroupId: NullInteger read FGroupId write FGroupId;

    [ForeignJoinColumn('PermissionId', '[Permission]', 'PermissionId', [fsOnDeleteCascade, fsOnUpdateCascade])]
    [Column]
    property PermissionId: NullInteger read FPermissionId write FPermissionId;

    [Column]
    property RUG: NullInteger read FRUG write FRUG;
  end;

  TRoleUserGroupPermissionExt = class(TRoleUserGroupPermission)
  private
    FUsername: string;
    FGroupName: string;
    FRoleName: string;
    FPermissionName : string;
  public
  published
    property GroupName: string read FGroupName write FGroupName;
    property RoleName: string read FRoleName write FRoleName;
    property Username: string read FUsername write FUsername;
    property PermissionName: string read FPermissionName write FPermissionName;
  end;

  [Entity]
  [Table('TSessionTokens')]
  TSessionTokens = class(TBaseModel)
  private
    FTokenGuid : NullString;
    FUserId : NullInteger;
    FStartTime : NullDateTime;
    FLastAccess : NullDateTime;
  published
    [Column('TokenGuid', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 50, 0, 0, 'Primary Key')]
    property TokenGuid: NullString read FTokenGuid write FTokenGuid;
    [Column]
    [ForeignJoinColumn('UserId', '[User]', 'UserId', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    property UserId: NullInteger read FUserId write FUserId;
    [Column]
    property StartTime: NullDateTime read FStartTime write FStartTime;
    [Column]
    property LastAccess: NullDateTime read FLastAccess write FLastAccess;
  end;


  [Entity]
  [Table('[Title]')]
  TTitle = class(TBaseModel)
  private
    FTitleId: Integer;
    FCompanyId: NullInteger;
    FTitleName: NullString;
    FTitleNameEng: NullString;
    FParentTitleId: NullInteger;
    FIsHeadShip: NullBool;
  published
    [Column('TitleId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property TitleId: Integer read FTitleId write FTitleId;
    [Column]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column([], 50, 0, 0, 'Ünvan')]
    property TitleName: NullString read FTitleName write FTitleName;
    [Column([], 50, 0, 0, 'Ünvan (ingilizce)')]
    property TitleNameEng: NullString read FTitleNameEng write FTitleNameEng;
    [Column]
    property ParentTitleId: NullInteger read FParentTitleId write FParentTitleId;
    [Column([], 0, 0, 0, 'Müdürlük mü?')]
    property IsHeadShip: NullBool read FIsHeadShip write FIsHeadShip;
  end;

  [Entity]
  [Table('Department')]
  TDepartment = class(TBaseModel)
  private
    FDepartmentId: Integer;
    FCompanyId: NullInteger;
    FParentId: NullInteger;
    FName: NullString;
    FDepartmentName: NullString;
    FDepartmentManagerTitleId: Integer;
    function GetCompanyName : string;
    function GetTitleName : string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CompanyId')]
    FCompany : TCompany;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'TitleId')]
    FTitle : TTitle;
  published
    [Column('DepartmentId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    [Id]
    property DepartmentId: Integer read FDepartmentId write FDepartmentId;
    [Column]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column]
    property ParentId: NullInteger read FParentId write FParentId;
    [Column([], 50, 0, 0)]
    property DepartmentName: NullString read FDepartmentName write FDepartmentName;
    [Column('DepartmentManagerTitleId', [], 0, 0, 0, '')]
    property TitleId: Integer read FDepartmentManagerTitleId write FDepartmentManagerTitleId;

    property CompanyName: string read GetCompanyName;
    property TitleName: string read GetTitleName;
  end;

  [Entity]
  [Table('Employee')]
  TEmployee = class(TBaseModel)
  private
    FEmployeeId: Integer;
    FCompanyId: NullInteger;
    FCompanyIdNumber: NullString;
    FEmployeeName: NullString;
    FEmployeeSurName: NullString;
    FTitleId: NullInteger;
    FGender: NullInteger; //TGenders;
    FMaritalStatus: NullInteger;
    FTCIdNumber: NullString;
    FPassportNumber: NullString;
    FSgkRegNumber: NullString;
    FMinimumWage: NullBool;
    FNetWage: NullBool;
    FWagePeriod: NullInteger; //TWagePeriods;
    FIncomeTaxExemptionGroupId: NullInteger;
    FEmploymentDate: NullDate;
    FRetired : NullBool;
    FRetirementDate: NullDate;
    FSgkGroup: NullInteger;
    FWageCurrencyId: NullInteger;
    FWageStampDutyOk: NullBool;
    FBonusStampDutyOk: NullBool;
    FBankId: NullInteger;
    FBankAccountNumber: NullString;
    FNickName: NullString;
    FIdFatherName: NullString;
    FIdBirthPlace: NullString;
    FIdBirthDate: NullDate;
    FIdVolumeNo: NullString;
    FIdMotherMaidenName: NullString;
    FIdReligion: NullString;
    FIdSerialNumber: NullString;
    FIdSequenceNo: NullString;
    FIdMotherName: NullString;
    FIdFamilyOrderNo: NullString;
    FIdOrderNo: NullString;
    FIdIssuePlace: NullString;
    FIdRegistrationNumber: NullString;
    FIdRegistrationReason: NullString;
    FIdRegistrationDate: NullDate;
    FPictureName: NullString;
    FIdCardImageFilename: NullString;
    FBloodType: NullString;
    FAdrDistrict: NullString;
    //FAdrCityId: NullInteger;
    FAdrTownId: NullInteger;
    FAdrPostCode: NullString;
    FAdrStreet: NullString;
    FAddress: NullString;
    FPhoneMobile: NullString;
    FPhoneHome: NullString;
    FPhoneOffice: NullString;
    FPhoneMobileCompany: NullString;
    FPrivateEMail: NullString;
    FCompanyEMail: NullString;
    FUnionMembered: NullString;
    FChildrenCount: NullInteger;
    FNationalityId: NullInteger;
    FTCIdNumberVerified: Boolean;

    function GetCompanyName : string;
    function GetNationality : string;
    function GetAdrTownName: string;
    function GetTitle: string;

  public
    ///  TCompany'deki ve TEmployee'deki isimler CompanyId olmak zorunda
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CompanyId')]
    FCompany : TCompany;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'TitleId')]
    FTitle : TTitle;
    //FWageCurrency : TCurrency;
    ///
    ///  TTown'daki ve TEmployee'deki isimler TownId olmak zorunda
    [ManyToOneAttribute(false, [ckCascadeMerge], 'TownId')]
    FAdrTown : TTown;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CountryId')]
    FNationality : TCountry;
  published
    [Column('EmployeeId', [cpRequired, cpUnique, cpPrimaryKey, cpNotNull], 0, 0)]
    [AutoGenerated]
    [Id]
    property EmployeeId: Integer read FEmployeeId write FEmployeeId;
    [Column('CompanyId', [cpRequired], 0, 0, 'Personelin çalýþtýðý firma IDsi')]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column('CompanyIdNumber', [], 20, 'Firma sicil numarasý')]
    property CompanyIdNumber: NullString read FCompanyIdNumber write FCompanyIdNumber;
    [Column('EmployeeName', [cpRequired], 30, 'Çalýþan önadý')]
    property EmployeeName: NullString read FEmployeeName write FEmployeeName;
    [Column('EmployeeSurName', [cpRequired], 30, 'Çalýþan soyadý')]
    property EmployeeSurName: NullString read FEmployeeSurName write FEmployeeSurName;
    [Column('TitleId', [], 0, 0, 'Ünvan Id')]
    [ForeignJoinColumn('TitleId', '[[Title]', 'TitleId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property TitleId: NullInteger read FTitleId write FTitleId;
    [Column('Gender', [], 0, 0, 'Personelin cinsiyeti Erkek=1, Kadýn=2, Diðer=3')]
    property Gender: NullInteger{TGenders} read FGender write FGender;
    [Column('MaritalStatus', [], 0, 0, 'Personelin medeni durumu Bekar=1, Evli=2, Boþanmýþ=3')]
    property MaritalStatus: NullInteger read FMaritalStatus write FMaritalStatus;
    [Column('TCIdNumber', [], 20, 'TC Kimlik numarasý')]
    property TCIdNumber: NullString read FTCIdNumber write FTCIdNumber;
    [Column('TCIdNumberVerified', [], 0, 'TC Kimlik numarasý kontrol edildi')]
    property TCIdNumberVerified: Boolean read FTCIdNumberVerified write FTCIdNumberVerified;
    [Column('PassportNumber', [], 20, 'Pasaport numarasý')]
    property PassportNumber: NullString read FPassportNumber write FPassportNumber;
    [Column('SgkRegNumber', [], 20, 'SGK sicil numarasý')]
    property SgkRegNumber: NullString read FSgkRegNumber write FSgkRegNumber;
    [Column('EmploymentDate', [], 0, 0, 'Ýþe baþlama tarihi')]
    property EmploymentDate: NullDate read FEmploymentDate write FEmploymentDate;
    [Column('Retired', [], 0, 0, 'Emekli mi?')]
    property Retired : NullBool read FRetired write FRetired;
    [Column('RetirementDate', [], 0, 0, 'Ýþten ayrýlýþ tarihi')]
    property RetirementDate: NullDate read FRetirementDate write FRetirementDate;
    [Column('SgkGroupId', [], 0, 0, 'Sgk grubu')]
    property SgkGroupId: NullInteger read FSgkGroup write FSgkGroup;
    [Column('WageCurrencyId', [], 0, 0, 'Ücret döviz cinsi')]
    [ForeignJoinColumn('WageCurrencyId', '[Currency]', 'WageCurrencyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property WageCurrencyId: NullInteger read FWageCurrencyId write FWageCurrencyId;
    [Column('NetWage', [], 0, 0, 'Net Ücret mi?')]
    property NetWage: NullBool read FNetWage write FNetWage;
    [Column('IncomeTaxExemptionGroupId', [], 0, 0, 'Gelir vergisi muafiyet grubu ID')]
    //[ForeignJoinColumn('IncomeTaxExemptionGroupId', '[IncomeTaxExemptionGroup]', 'IncomeTaxExemptionGroupId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property IncomeTaxExemptionGroupId: NullInteger read FIncomeTaxExemptionGroupId write FIncomeTaxExemptionGroupId;
    [Column('WagePeriod', [], 0, 0, 'Ücret hesaplama periyodu')]
    property WagePeriod: NullInteger read FWagePeriod write FWagePeriod;
    [Column('WageStampDutyOk', [], 0, 0, 'Ücretten damga vergisi kesiliyor mu?')]
    property WageStampDutyOk: NullBool read FWageStampDutyOk write FWageStampDutyOk;
    [Column('BonusStampDutyOk', [], 0, 0, 'Ýkramiyeden damga vergisi kesiliyor mu?')]
    property BonusStampDutyOk: NullBool read FBonusStampDutyOk write FBonusStampDutyOk;
    [Column('MinimumWage', [], 0, 0, 'Asgari Ücret mi?')]
    property MinimumWage: NullBool read FMinimumWage write FMinimumWage;
    [Column('BankId', [], 0, 0, 'Hesap yatýrýlan banka ID')]
    [ForeignJoinColumn('BankId', '[Bank]', 'BankId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property BankId: NullInteger read FBankId write FBankId;
    [Column('BankAccountNumber', [], 20, 'Personelin banka hesap numarasý')]
    property BankAccountNumber: NullString read FBankAccountNumber write FBankAccountNumber;
    [Column('NickName', [], 20, 'Takma ad')]
    property NickName: NullString read FNickName write FNickName;
    [Column('NationalityId', [], 0, 'Uyruðu')]
    [ForeignJoinColumn('NationalityId', '[Country]', 'CountryId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CountryId: NullInteger read FNationalityId write FNationalityId;
    [Column('IdSerialNumber', [], 20, 'NC seri numarasý')]
    property IdSerialNumber: NullString read FIdSerialNumber write FIdSerialNumber;
    [Column('IdFatherName', [], 50, 'NC Baba adý')]
    property IdFatherName: NullString read FIdFatherName write FIdFatherName;
    [Column('IdMotherName', [], 50, 'NC Ana adý')]
    property IdMotherName: NullString read FIdMotherName write FIdMotherName;
    [Column('IdBirthPlace', [], 50, 'NC Doðum yeri')]
    property IdBirthPlace: NullString read FIdBirthPlace write FIdBirthPlace;
    [Column('IdBirthDate', [], 50, 'NC Doðum yeri')]
    property IdBirthDate: NullDate read FIdBirthDate write FIdBirthDate;
    [Column('IdReligion', [], 20, 'Dini')]
    property IdReligion: NullString read FIdReligion write FIdReligion;
    [Column('IdMotherMaidenName', [], 30, 'NC Anne kýzlýk soyadý')]
    property IdMotherMaidenName: NullString read FIdMotherMaidenName write FIdMotherMaidenName;
    [Column('IdSequenceNo', [], 20, 'NC Sýra numarasý')]
    property IdSequenceNo: NullString read FIdSequenceNo write FIdSequenceNo;
    [Column('IdVolumeNo', [], 20, 'NC Cilt numarasý')]
    property IdVolumeNo: NullString read FIdVolumeNo write FIdVolumeNo;
    [Column('IdFamilyOrderNo', [], 20, 'NC Aile sýra numarasý')]
    property IdFamilyOrderNo: NullString read FIdFamilyOrderNo write FIdFamilyOrderNo;
    [Column('IdOrderNo', [], 20, 'NC Sýra numarasý')]
    property IdOrderNo: NullString read FIdOrderNo write FIdOrderNo;
    [Column('IdIssuePlace', [], 30, 'NC Verildiði yer')]
    property IdIssuePlace: NullString read FIdIssuePlace write FIdIssuePlace;
    [Column('IdRegistrationNumber', [], 20, 'NC Kayýt numarasý')]
    property IdRegistrationNumber: NullString read FIdRegistrationNumber write FIdRegistrationNumber;
    [Column('IdRegistrationReason', [], 20, 'NC Veriliþ sebebi')]
    property IdRegistrationReason: NullString read FIdRegistrationReason write FIdRegistrationReason;
    [Column('IdRegistrationDate', [], 0, 'NC Veriliþ tarihi')]
    property IdRegistrationDate: NullDate read FIdRegistrationDate write FIdRegistrationDate;
    [Column('PictureFileName', [], 100, 'Resim dosyasý adý')]
    property PictureFileName: NullString read FPictureName write FPictureName;
    [Column('IdCardImageFilename', [], 100, 'Kimlik kartý taranmýþ resim dosyasý adý')]
    property IdCardImageFilename: NullString read FIdCardImageFilename write FIdCardImageFilename;

    [Column('BloodType', [], 20, 'Kan grubu')]
    property BloodType: NullString read FBloodType write FBloodType;
    [Column('AdrDistrict', [], 30, 'Mahalle')]
    property AdrDistrict: NullString read FAdrDistrict write FAdrDistrict;
    [Column('AdrTownId', [], 30, 'Ýlçe')]
    [ForeignJoinColumn('AdrTownId', '[AdrTown]', 'TownId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property TownId: NullInteger read FAdrTownId write FAdrTownId;
    //[Column('AdrCityId', [], 0, 'Ýl')]
    //property AdrCityId: NullInteger read FAdrCityId write FAdrCityId;
    [Column('AdrPostCode', [], 30, 'Posta kodu')]
    property AdrPostCode: NullString read FAdrPostCode write FAdrPostCode;
    [Column('AdrStreet', [], 50, 'Cadde/Sokak')]
    property AdrStreet: NullString read FAdrStreet write FAdrStreet;
    [Column('Address', [], 50, 'Apt. adý-kapý numarasý')]
    property Address: NullString read FAddress write FAddress;

    [Column('PhoneMobile', [], 20, 'Cep telefonu')]
    property PhoneMobile: NullString read FPhoneMobile write FPhoneMobile;
    [Column('PhoneHome', [], 20, 'Ev telefonu')]
    property PhoneHome: NullString read FPhoneHome write FPhoneHome;
    [Column('PhoneOffice', [], 20, 'Þirket içi telefon')]
    property PhoneOffice: NullString read FPhoneOffice write FPhoneOffice;
    [Column('PhoneMobileCompany', [], 20, 'Þirket cep telefonu')]
    property PhoneMobileCompany: NullString read FPhoneMobileCompany write FPhoneMobileCompany;
    [Column('PrivateEMail', [], 100, 'Özel e-posta')]
    property PrivateEMail: NullString read FPrivateEMail write FPrivateEMail;
    [Column('CompanyEMail', [], 100, 'Þirket e-postasý')]
    property CompanyEMail: NullString read FCompanyEMail write FCompanyEMail;

    [Column('UnionMembered', [], 50, 'Sendika')]
    property UnionMembered: NullString read FUnionMembered write FUnionMembered;

    [Column('ChildrenCount', [], 0, 'Çocuk sayýsý')]
    property ChildrenCount: NullInteger read FChildrenCount write FChildrenCount;

    property CompanyName : string read GetCompanyName;
    property Title: string read GetTitle;
    property AdrTown: string read GetAdrTownName;
    property Nationality: string read GetNationality;
  end;

  [Entity]
  [Table('EmployeeFamilyMember')]
  TEmployeeFamilyMember = class(TBaseModel)
  private
    FEmployeeFamilyMemberId: Integer;
    FEmployeeId: NullInteger;
    FIdentityNumber: NullString;
    FName: NullString;
    FSurname: NullString;
    FRelationshipTypeId: NullInteger;
    FGender: NullInteger; //TGenders;
    FBirthDate: NullDate;
    FIsStudent: NullBool;
    FEducation: NullString;
    FJob: NullString;
    FWorking: NullBool;
    FAlive: NullBool;
    FIncomeStatus: NullBool;
    FMobilePhone: NullString;
    FBeLiableToLookAfter : NullBool;
  published
    [Column('EmployeeFamilyMemberId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property EmployeeFamilyMemberId: Integer read FEmployeeFamilyMemberId write FEmployeeFamilyMemberId;
    [Column]
    [ForeignJoinColumn('EmployeeId', 'Employee', 'EmployeeId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property EmployeeId: NullInteger read FEmployeeId write FEmployeeId;
    [Column([], 50, 0, 0, 'TC Kimlik no')]
    property IdentityNumber: NullString read FIdentityNumber write FIdentityNumber;
    [Column([], 50, 0, 0, 'Adý')]
    property Name: NullString read FName write FName;
    [Column([], 50, 0, 0, 'Soyadý')]
    property Surname: NullString read FSurname write FSurname;
    [Column([], 50, 0, 0, 'Akrabalýk türü')]
    [ForeignJoinColumn('RelationshipTypeId', 'RelationshipType', 'RelationshipTypeId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property RelationshipTypeId: NullInteger read FRelationshipTypeId write FRelationshipTypeId;
    [Column([], 0, 0, 0, 'Cinsiyet')]
    property Gender: NullInteger {TGenders} read FGender write FGender;
    [Column([], 0, 0, 0, 'Doðum tarihi')]
    property BirthDate: NullDate read FBirthDate write FBirthDate;
    [Column([], 0, 0, 0, 'Öðrenci mi')]
    property IsStudent: NullBool read FIsStudent write FIsStudent;
    [Column([], 50, 0, 0, 'Öðretim durumu')]
    property Education: NullString read FEducation write FEducation;
    [Column([], 50, 0, 0, 'Çalýþtýðý iþi')]
    property Job: NullString read FJob write FJob;
    [Column([], 0, 0, 0, 'Çalýþýyor mu?')]
    property Working: NullBool read FWorking write FWorking;
    [Column([], 0, 0, 0, 'Hayatta mý?')]
    property Alive: NullBool read FAlive write FAlive;
    [Column([], 50, 0, 0, 'Gelir durumu')]
    property IncomeStatus: NullBool read FIncomeStatus write FIncomeStatus;
    [Column([], 20, 0, 0, 'Cep telefonu')]
    property MobilePhone: NullString read FMobilePhone write FMobilePhone;
    [Column([], 0, 0, 0, 'Bakmakla yükümlü olduðu biri mi?')]
    property BeLiableToLookAfter: NullBool read FBeLiableToLookAfter write FBeLiableToLookAfter;
  end;

  [Entity]
  [Table('RelationshipType')]
  TRelationshipType = class(TBaseModel)
  private
    FRelationshipTypeId: Integer;
    //FCompanyId: NullInteger;
    FRelationshipTypeName : NullString;
  published
    [Column('RelationshipTypeId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property RelationshipTypeId: Integer read FRelationshipTypeId write FRelationshipTypeId;
    {[Column]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;}
    [Column([], 50, 0, 0)]
    property RelationshipTypeName: NullString read FRelationshipTypeName write FRelationshipTypeName;
  end;

  [Entity]
  [Table('[EmployeePayroll]')]
  TEmployeePayroll = class(TBaseModel)
  private
    FEmployeePayrollId: Integer;
    FEmployeeId: NullInteger;
    FPayrollYear: NullInteger;
    FPayrollPeriod: NullInteger;
    FCurrencyId: NullInteger;
    FCurrencyRate: NullExtended;
    FOWage: NullExtended;
    FIsOWageNet: NullBool;
    FNetWage: NullExtended;
    FGrossWage: NullExtended;
    FNWDay: NullInteger;
    FNWHour: NullInteger;
    FNWAmount: NullExtended;
    FOvertimeW1Hour: NullInteger;
    FOvertimeW1Day: NullInteger;
    FOvertimeW1Amount: NullExtended;
    FOvertimeW2Hour: NullInteger;
    FOvertimeW2Day: NullInteger;
    FOvertimeW2Amount: NullExtended;
    FOvertimeW3Hour: NullInteger;
    FOvertimeW3Day: NullInteger;
    FOvertimeW3Amount: NullExtended;
    FWeekendHour: NullInteger;
    FWeekendDay: NullInteger;
    FWeekendAmount: NullExtended;
    FFeastHour: NullInteger;
    FFeastDay: NullInteger;
    FFeastAmount: NullExtended;
    FHolidayHour: NullInteger;
    FHolidayDay: NullInteger;
    FHolidayAmount: NullExtended;

    FSgkDayCount: NullInteger;

    FTotalOtherWages: NullExtended;
    FTotalOtherCuts: NullExtended;
    FSgkCutBase: NullExtended;
    FSgkCutAmountEmployer: NullExtended;
    FSgkCutAmountEmployee: NullExtended;
    FStampDutyRate: NullExtended;
    FStampDutyAmount: NullExtended;
    FIncomeTaxDeduction: NullExtended;
    FIncomeTaxBase: NullExtended;
    FCumulativeIncomeTaxBase: NullExtended;
    FIncomeTaxAmount: NullExtended;
    FMinLivingAllowance: NullExtended;
    FNetPayment: NullExtended;
    FPayrollNumber: NullInteger;
    FHeaderFlags: NullInteger;
    FBonusCurrencyId: NullInteger;
    FBonusCurrencyRate: NullExtended;
    FOBonusAmount: NullExtended;
    FNetBonus: NullExtended;
    FGrossBonus: NullExtended;
    FSgkCutEmployer1: NullExtended;
    FSgkCutEmployer2: NullExtended;
    FSgkCutEmployer3: NullExtended;
    FSgkCutEmployer4: NullExtended;
    FSgkCutEmployee1: NullExtended;
    FSgkCutEmployee2: NullExtended;
    FSgkCutEmployee3: NullExtended;
    FSgkCutEmployee4: NullExtended;
  published
    [Column('EmployeePayrollId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property EmployeePayrollId: Integer read FEmployeePayrollId write FEmployeePayrollId;
    [Column]
    [ForeignJoinColumn('EmployeeId', 'Employee', 'EmployeeId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property EmployeeId: NullInteger read FEmployeeId write FEmployeeId;
    [Column([], 0, 0, 0, 'Bordro yýlý')]
    property PayrollYear: NullInteger read FPayrollYear write FPayrollYear;
    [Column([], 0, 0, 0, 'Bordro dönemi')]
    property PayrollPeriod: NullInteger read FPayrollPeriod write FPayrollPeriod;
    [Column([], 0, 0, 0, 'Döviz kodu')]
    [ForeignJoinColumn('CurrencyId', '[Currency]', 'CurrencyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CurrencyId: NullInteger read FCurrencyId write FCurrencyId;
    [Column([], 16, 16, 6, 'Döviz kuru')]
    property CurrencyRate: NullExtended read FCurrencyRate write FCurrencyRate;
    [Column([], 16, 16, 4, 'Belirlenen ücret')]
    property OWage: NullExtended read FOWage write FOWage;
    [Column([], 0, 0, 0, 'Belirlenen ücret net ücret mi?')]
    property IsOWageNet: NullBool read FIsOWageNet write FIsOWageNet;
    [Column([], 16, 16, 4, 'Net ücreti')]
    property NetWage: NullExtended read FNetWage write FNetWage;
    [Column([], 16, 16, 4, 'Brüt ücreti')]
    property GrossWage: NullExtended read FGrossWage write FGrossWage;

    [Column([], 0, 0, 0, 'Normal çalýþma GÜN')]
    property NWDay: NullInteger read FNWDay write FNWDay;
    [Column([], 0, 0, 0, 'Normal çalýþma SAAT')]
    property NWHour: NullInteger read FNWHour write FNWHour;
    [Column([], 16, 16, 4, 'Normal çalýþma TUTARI')]
    property NWAmount: NullExtended read FNWAmount write FNWAmount;

    [Column([], 0, 0, 0, 'Fazla çalýþma-1 GÜN')]
    property OvertimeW1Day: NullInteger read FOvertimeW1Day write FOvertimeW1Day;
    [Column([], 0, 0, 0, 'Fazla çalýþma-1 SAAT')]
    property OvertimeW1Hour: NullInteger read FOvertimeW1Hour write FOvertimeW1Hour;
    [Column([], 16, 16, 4, 'Fazla çalýþma-1 TUTARI')]
    property OvertimeW1Amount: NullExtended read FOvertimeW1Amount write FOvertimeW1Amount;

    [Column([], 0, 0, 0, 'Fazla çalýþma-2 GÜN')]
    property OvertimeW2Day: NullInteger read FOvertimeW2Day write FOvertimeW2Day;
    [Column([], 0, 0, 0, 'Fazla çalýþma-2 SAAT')]
    property OvertimeW2Hour: NullInteger read FOvertimeW2Hour write FOvertimeW2Hour;
    [Column([], 16, 16, 4, 'Fazla çalýþma-2 TUTARI')]
    property OvertimeW2Amount: NullExtended read FOvertimeW2Amount write FOvertimeW2Amount;

    [Column([], 0, 0, 0, 'Fazla çalýþma-3 GÜN')]
    property OvertimeW3Day: NullInteger read FOvertimeW3Day write FOvertimeW3Day;
    [Column([], 0, 0, 0, 'Fazla çalýþma-3 SAAT')]
    property OvertimeW3Hour: NullInteger read FOvertimeW3Hour write FOvertimeW3Hour;
    [Column([], 16, 16, 4, 'Fazla çalýþma-3 TUTARI')]
    property OvertimeW3Amount: NullExtended read FOvertimeW3Amount write FOvertimeW3Amount;

    [Column([], 0, 0, 0, 'Hafta tatili GÜN')]
    property WeekendDay: NullInteger read FWeekendDay write FWeekendDay;
    [Column([], 0, 0, 0, 'Hafta tatili SAAT')]
    property WeekendHour: NullInteger read FWeekendHour write FWeekendHour;
    [Column([], 16, 16, 4, 'Hafta tatili TUTARI')]
    property WeekendAmount: NullExtended read FWeekendAmount write FWeekendAmount;

    [Column([], 0, 0, 0, 'Bayram tatili GÜN')]
    property FeastDay: NullInteger read FFeastDay write FFeastDay;
    [Column([], 0, 0, 0, 'Bayram tatili SAAT')]
    property FeastHour: NullInteger read FFeastHour write FFeastHour;
    [Column([], 16, 16, 4, 'Bayram tatili TUTARI')]
    property FeastAmount: NullExtended read FFeastAmount write FFeastAmount;

    [Column([], 0, 0, 0, 'Ýzin GÜN')]
    property HolidayDay: NullInteger read FHolidayDay write FHolidayDay;
    [Column([], 0, 0, 0, 'Ýzin SAAT')]
    property HolidayHour: NullInteger read FHolidayHour write FHolidayHour;
    [Column([], 16, 16, 4, 'Ýzin TUTARI')]
    property HolidayAmount: NullExtended read FHolidayAmount write FHolidayAmount;

    [Column([], 0, 0, 0, 'Sgk Gün Sayýsý')]
    property SgkDayCount: NullInteger read FSgkDayCount write FSgkDayCount;
    [Column([], 16, 16, 2, 'Toplam Diðer Gelirler TUTARI')]
    property TotalOtherWages: NullExtended read FTotalOtherWages write FTotalOtherWages;
    [Column([], 16, 16, 2, 'Toplam Diðer Kesintiler TUTARI')]
    property TotalOtherCuts: NullExtended read FTotalOtherCuts write FTotalOtherCuts;
    [Column([], 16, 16, 2, 'SGK Kesintisi Matrah TUTARI')]
    property SgkCutBase: NullExtended read FSgkCutBase write FSgkCutBase;

    [Column([], 16, 16, 2, 'SGK Kesintisi Ýþveren Payý TUTARI')]
    property SgkCutAmountEmployer: NullExtended read FSgkCutAmountEmployer write FSgkCutAmountEmployer;
    [Column([], 16, 16, 2, 'SGK Kesintisi Çalýþan Payý TUTARI')]
    property SgkCutAmountEmployee: NullExtended read FSgkCutAmountEmployee write FSgkCutAmountEmployee;

    [Column([], 16, 16, 2, 'Damga Vergisi Oraný (%)')]
    property StampDutyRate: NullExtended read FStampDutyRate write FStampDutyRate;
    [Column([], 16, 16, 2, 'Damga Vergisi Tutarý')]
    property StampDutyAmount: NullExtended read FStampDutyAmount write FStampDutyAmount;

    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi')]
    property IncomeTaxDeduction: NullExtended read FIncomeTaxDeduction write FIncomeTaxDeduction;
    [Column([], 16, 16, 2, 'Gelir Vergisi MATRAHI')]
    property IncomeTaxBase: NullExtended read FIncomeTaxBase write FIncomeTaxBase;
    [Column([], 16, 16, 2, 'Kümülatif Gelir Vergisi Matrahý')]
    property CumulativeIncomeTaxBase: NullExtended read FCumulativeIncomeTaxBase write FCumulativeIncomeTaxBase;
    [Column([], 16, 16, 2, 'Gelir Vergisi Tutarý')]
    property IncomeTaxAmount: NullExtended read FIncomeTaxAmount write FIncomeTaxAmount;
    [Column([], 16, 16, 2, 'Asgari Geçim Ýndirimi')]
    property MinLivingAllowance: NullExtended read FMinLivingAllowance write FMinLivingAllowance;
    [Column([], 16, 16, 2, 'Net Ödeme Tutarý')]
    property NetPayment: NullExtended read FNetPayment write FNetPayment;

    [Column([], 0, 0, 0, 'Bordro no')]
    property PayrollNumber: NullInteger read FPayrollNumber write FPayrollNumber;
    [Column([], 0, 0, 0, 'Header flags')]
    property HeaderFlags: NullInteger read FHeaderFlags write FHeaderFlags;

    [Column([], 0, 0, 0, 'Ýkramiye Döviz kodu')]
    [ForeignJoinColumn('BonusCurrencyId', '[Currency]', 'WageCurrencyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property BonusCurrencyId: NullInteger read FBonusCurrencyId write FBonusCurrencyId;
    [Column([], 16, 16, 6, 'Ýkramiye Döviz kuru')]
    property BonusCurrencyRate: NullExtended read FBonusCurrencyRate write FBonusCurrencyRate;
    [Column([], 16, 16, 6, 'Org. Ýkramiye')]
    property OBonusAmount: NullExtended read FOBonusAmount write FOBonusAmount;

    [Column([], 16, 16, 6, 'Net Ýkramiye Tutarý')]
    property NetBonus: NullExtended read FNetBonus write FNetBonus;
    [Column([], 16, 16, 6, 'Brüt Ýkramiye Tutarý')]
    property GrossBonus: NullExtended read FGrossBonus write FGrossBonus;
    [Column([], 16, 16, 6, 'SGK Kesintisi Çalýþan payý-1')]
    property SgkCutEmployee1: NullExtended read FSgkCutEmployee1 write FSgkCutEmployee1;
    [Column([], 16, 16, 6, 'SGK Kesintisi Çalýþan payý-2')]
    property SgkCutEmployee2: NullExtended read FSgkCutEmployee2 write FSgkCutEmployee2;
    [Column([], 16, 16, 6, 'SGK Kesintisi Çalýþan payý-3')]
    property SgkCutEmployee3: NullExtended read FSgkCutEmployee3 write FSgkCutEmployee3;
    [Column([], 16, 16, 6, 'SGK Kesintisi Çalýþan payý-4')]
    property SgkCutEmployee4: NullExtended read FSgkCutEmployee4 write FSgkCutEmployee4;

    [Column([], 16, 16, 6, 'SGK Kesintisi Ýþveren payý-1')]
    property SgkCutEmployer1: NullExtended read FSgkCutEmployer1 write FSgkCutEmployer1;
    [Column([], 16, 16, 6, 'SGK Kesintisi Ýþveren payý-2')]
    property SgkCutEmployer2: NullExtended read FSgkCutEmployer2 write FSgkCutEmployer2;
    [Column([], 16, 16, 6, 'SGK Kesintisi Ýþveren payý-3')]
    property SgkCutEmployer3: NullExtended read FSgkCutEmployer3 write FSgkCutEmployer3;
    [Column([], 16, 16, 6, 'SGK Kesintisi Ýþveren payý-4')]
    property SgkCutEmployer4: NullExtended read FSgkCutEmployer4 write FSgkCutEmployer4;

  end;

  [Entity]
  [Table('[OthIncomeOutcomeDef]')]
  TOthIncomeOutcomeDef = class(TBaseModel)
  private
    FOthIncomeOutcomeDef: Integer;
    FIncomeOutcome: NullInteger;
    FCode: NullString;
    FDescription: NullString;
    FComputationType: TComputationType;
    FIncomeTaxOk: NullBool;
    FSgkCutOk: NullBool;
    FWageStampDutyOk: NullBool;
    FOtvCutOk: NullBool;
    FAmount1: NullExtended;
    FAmount2: NullExtended;
    FAmount3: NullExtended;
    FPercentage1: NullExtended;
    FPercentage2: NullExtended;
    FPercentage3: NullExtended;
    FCurrencyId: NullInteger;
    FIsNet: NullBool;
    FComputationText: NullString;
    FOtvCutPercentage: NullExtended;
    FCompanyId: NullInteger;
    function GetCompanyCode: string;
    function GetCompanyName: string;
    function GetCurrencyName: string;
    function GetCurrencyCode: string;
    function GetComputationTypeText: string;
    function GetIncomeOutcomeText: string;
  public
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CompanyId')]
    FCompany : TCompany;
    [ManyToOneAttribute(false, [ckCascadeMerge], 'CurrencyId')]
    FCurrency : TCurrency;
  published
    [Column('OthIncomeOutcomeDefId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property OthIncomeOutcomeDefId: Integer read FOthIncomeOutcomeDef write FOthIncomeOutcomeDef;
    [Column]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column([], 0, 0, 0, 'Gelir/gider ayrýmý; 0: Gelir, 1:Gider')]
    property IncomeOutcome: NullInteger read FIncomeOutcome write FIncomeOutcome;
    [Column([], 10, 0, 0, 'Diðer gelir/gider kodu')]
    property Code: NullString read FCode write FCode;
    [Column([], 50, 0, 0, 'Diðer gelir/gider açýklamasý')]
    property Description: NullString read FDescription write FDescription;
    [Column([], 0, 0, 0, 'Hesaplama türü : 0: Tutar1, 1:Yüzde1, 2:Hesaplama')]
    property ComputationType: TComputationType read FComputationType write FComputationType;
    [Column([], 0, 0, 0, 'Gelir vergisi var mý?')]
    property IncomeTaxOk: NullBool read FIncomeTaxOk write FIncomeTaxOk;
    [Column([], 0, 0, 0, 'SGK kesintisi var mý?')]
    property SgkCutOk: NullBool read FSgkCutOk write FSgkCutOk;
    [Column([], 0, 0, 0, 'Damga vergisi var mý?')]
    property WageStampDutyOk: NullBool read FWageStampDutyOk write FWageStampDutyOk;
    [Column([], 0, 0, 0, 'ÖTV kesintisi var mý?')]
    property OtvCutOk: NullBool read FOtvCutOk write FOtvCutOk;
    [Column([], 12, 16, 4, 'ÖTV Kesinti yüzdesi')]
    property OtvCutPercentage: NullExtended read FOtvCutPercentage write FOtvCutPercentage;
    [Column([], 12, 16, 4, 'Tutar1')]
    property Amount1: NullExtended read FAmount1 write FAmount1;
    [Column([], 12, 16, 4, 'Tutar2')]
    property Amount2: NullExtended read FAmount2 write FAmount2;
    [Column([], 12, 16, 4, 'Tutar3')]
    property Amount3: NullExtended read FAmount3 write FAmount3;
    [Column([], 12, 16, 4, 'Yüzdelik1')]
    property Percentage1: NullExtended read FPercentage1 write FPercentage1;
    [Column([], 12, 16, 4, 'Yüzdelik2')]
    property Percentage2: NullExtended read FPercentage2 write FPercentage2;
    [Column([], 12, 16, 4, 'Yüzdelik3')]
    property Percentage3: NullExtended read FPercentage3 write FPercentage3;
    [Column([], 0, 0, 0, 'Döviz cinsi')]
    [ForeignJoinColumn('CurrencyId', 'Currency', 'CurrencyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CurrencyId: NullInteger read FCurrencyId write FCurrencyId;
    [Column([], 0, 0, 0, 'Ek ödeme kesinti net mi?')]
    property IsNet: NullBool read FIsNet write FIsNet;
    [Column([], 2000, 0, 0, 'Hesaplama algoritmasý')]
    property ComputationText: NullString read FComputationText write FComputationText;

    property CompanyName: string read GetCompanyName;
    property CompanyCode: string read GetCompanyCode;
    property CurrencyName: string read GetCurrencyName;
    property CurrencyCode: string read GetCurrencyCode;
    property ComputationTypeText: string read GetComputationTypeText;
    property IncomeOutcomeText: string read GetIncomeOutcomeText;
  end;

  [Entity]
  [Table('[OthIncomeOutcome]')]
  TOthIncomeOutcome = class(TBaseModel)
  private
    FOthIncomeOutcomeId: Integer;
    FEmployeeId: NullInteger;
    FOthIncomeOutcomeDefId: NullInteger;
    FPayrollYear: NullInteger;
    FPayrollPeriod: NullInteger;
    FRefAmount: NullExtended;
    FCurrencyId: NullInteger;
    FCurrencyRate: NullExtended;
    FGrossAmount: NullExtended;
    FNetAmount: NullExtended;
    FDescription: NullString;
  published
    [Column('OthIncomeOutcomeId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property OthIncomeOutcomeId: Integer read FOthIncomeOutcomeId write FOthIncomeOutcomeId;
    [Column]
    [ForeignJoinColumn('EmployeeId', 'Employee', 'EmployeeId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property EmployeeId: NullInteger read FEmployeeId write FEmployeeId;
    [Column]
    [ForeignJoinColumn('OthIncomeOutcomeDefId', 'OthIncomeOutcomeDef', 'OthIncomeOutcomeDefId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property OthIncomeOutcomeDefId: NullInteger read FOthIncomeOutcomeDefId write FOthIncomeOutcomeDefId;
    [Column]
    property PayrollYear: NullInteger read FPayrollYear write FPayrollYear;
    [Column]
    property PayrollPeriod: NullInteger read FPayrollPeriod write FPayrollPeriod;
    [Column([], 16, 16, 4, 'Belirlenen Tutar')]
    property RefAmount: NullExtended read FRefAmount write FRefAmount;
    [Column([], 0, 0, 0, 'Döviz kodu')]
    [ForeignJoinColumn('CurrencyId', '[Currency]', 'WageCurrencyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CurrencyId: NullInteger read FCurrencyId write FCurrencyId;
    [Column([], 16, 16, 6, 'Döviz kuru')]
    property CurrencyRate: NullExtended read FCurrencyRate write FCurrencyRate;
    [Column([], 16, 16, 4, 'Brüt Tutar')]
    property GrossAmount: NullExtended read FGrossAmount write FGrossAmount;
    [Column([], 16, 16, 4, 'Net Tutar')]
    property NetAmount: NullExtended read FNetAmount write FNetAmount;
    [Column([], 50, 0, 0, 'Açýklama')]
    property Description: NullString read FDescription write FDescription;
  end;

  [Entity]
  [Table('[IncomeTaxPercentage]')]
  TIncomeTaxPercentage = class(TBaseModel)
  private
    FIncomeTaxPercentageId: Integer;
    FStartDate: NullDate;
    FAmountLimit: NullExtended;
    FPercentage: NullExtended;
  published
    [Column('IncomeTaxPercentageId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property IncomeTaxPercentageId: Integer read FIncomeTaxPercentageId write FIncomeTaxPercentageId;
    [Column]
    property StartDate: NullDate read FStartDate write FStartDate;
    [Column([], 16, 16, 4)]
    property AmountLimit: NullExtended read FAmountLimit write FAmountLimit;
    [Column([], 16, 16, 4)]
    property Percentage: NullExtended read FPercentage write FPercentage;
  end;

  [Entity]
  [Table('[SgkCutPercentage]')]
  TSgkCutPercentage = class(TBaseModel)
  private
    FSgkCutPercentageId: Integer;
    FStartDate: NullDate;
    FEmployeeGeneralHealth: NullExtended;
    FEmployeeInvalidityOldDeath: NullExtended;
    FEmployeeUnemployment: NullExtended;
    FEmployerGeneralHealth: NullExtended;
    FEmployerInvalidityOldDeath: NullExtended;
    FEmployerUnemployment: NullExtended;
    FEmployeeCutOth: NullExtended;
    FEmployerCutOth: NullExtended;
  published
    [Column('SgkCutPercentageId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property SgkCutPercentageId: Integer read FSgkCutPercentageId write FSgkCutPercentageId;
    [Column]
    property StartDate: NullDate read FStartDate write FStartDate;
    [Column([], 16, 16, 2, 'Genel Saðlýk Sigorta kesintisi Çalýþan Payý')]
    property EmployeeGeneralHealth: NullExtended read FEmployeeGeneralHealth write FEmployeeGeneralHealth;
    [Column([], 16, 16, 2, 'Malüllük Yaþlýlýk ve Ölüm sigorta kesintisi Çalýþan Payý')]
    property EmployeeInvalidityOldDeath: NullExtended read FEmployeeInvalidityOldDeath write FEmployeeInvalidityOldDeath;
    [Column([], 16, 16, 2, 'Ýþsizlik sigorta kesintisi Çalýþan Payý')]
    property EmployeeUnemployment: NullExtended read FEmployeeUnemployment write FEmployeeUnemployment;
    [Column([], 16, 16, 2, 'Diðer sigorta kesintisi Çalýþan Payý')]
    property EmployeeCutOth: NullExtended read FEmployeeCutOth write FEmployeeCutOth;

    [Column([], 16, 16, 2, 'Genel Saðlýk Sigorta kesintisi Ýþveren Payý')]
    property EmployerGeneralHealth: NullExtended read FEmployerGeneralHealth write FEmployerGeneralHealth;
    [Column([], 16, 16, 2, 'Malüllük Yaþlýlýk ve Ölüm sigorta kesintisi Ýþveren Payý')]
    property EmployerInvalidityOldDeath: NullExtended read FEmployerInvalidityOldDeath write FEmployerInvalidityOldDeath;
    [Column([], 16, 16, 2, 'Ýþsizlik sigorta kesintisi Ýþveren Payý')]
    property EmployerUnemployment: NullExtended read FEmployerUnemployment write FEmployerUnemployment;
    [Column([], 16, 16, 2, 'Diðer sigorta kesintisi Ýþveren Payý')]
    property EmployerCutOth: NullExtended read FEmployerCutOth write FEmployerCutOth;
  end;

  [Entity]
  [Table('[SgkHazardClassPremiumRate]')]
  TSgkHazardClassPremiumRate = class(TBaseModel)
  private
    FSgkHazardClassPremiumRate: Integer;
    FStartDate: NullDate;
    FClass_I: NullExtended;
    FClass_II: NullExtended;
    FClass_III: NullExtended;
    FClass_IV: NullExtended;
    FClass_V: NullExtended;
    FClass_VI: NullExtended;
    FClass_VII: NullExtended;
    FClass_VIII: NullExtended;
    FClass_IX: NullExtended;
    FClass_X: NullExtended;
    FClass_XI: NullExtended;
    FClass_XII: NullExtended;
  published
    [Column('SgkHazardClassPremiumRateId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property SgkHazardClassPremiumRateId: Integer read FSgkHazardClassPremiumRate write FSgkHazardClassPremiumRate;
    [Column]
    property StartDate: NullDate read FStartDate write FStartDate;
    [Column([], 16, 16, 2)]
    property Class_I: NullExtended read FClass_I write FClass_I;
    [Column([], 16, 16, 2)]
    property Class_II: NullExtended read FClass_II write FClass_II;
    [Column([], 16, 16, 2)]
    property Class_III: NullExtended read FClass_III write FClass_III;
    [Column([], 16, 16, 2)]
    property Class_IV: NullExtended read FClass_IV write FClass_IV;
    [Column([], 16, 16, 2)]
    property Class_V: NullExtended read FClass_V write FClass_V;
    [Column([], 16, 16, 2)]
    property Class_VI: NullExtended read FClass_VI write FClass_VI;
    [Column([], 16, 16, 2)]
    property Class_VII: NullExtended read FClass_VII write FClass_VII;
    [Column([], 16, 16, 2)]
    property Class_VIII: NullExtended read FClass_VIII write FClass_VIII;
    [Column([], 16, 16, 2)]
    property Class_IX: NullExtended read FClass_IX write FClass_IX;
    [Column([], 16, 16, 2)]
    property Class_X: NullExtended read FClass_X write FClass_X;
    [Column([], 16, 16, 2)]
    property Class_XI: NullExtended read FClass_XI write FClass_XI;
    [Column([], 16, 16, 2)]
    property Class_XII: NullExtended read FClass_XII write FClass_XII;
  end;

  [Entity]
  [Table('[CompanyInfo]')]
  TCompanyInfo = class(TBaseModel)
  private
    FCompanyInfoId: Integer;
    FCompanyId: NullInteger;
    FStartDate: NullDate;
    FCompanyHazardLevel: NullString;
    FBonusPeriods: NullString;
    FWorkHourOfADay: NullExtended;
    FWorkDaysOfAPeriod: NullExtended;
    FOvertimeDef1: NullString;
    FOvertimeDef2: NullString;
    FOvertimeDef3: NullString;
    FOvertimeRate1: NullExtended;
    FOvertimeRate2: NullExtended;
    FOvertimeRate3: NullExtended;
  published
    [Column('CompanyInfoId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property CompanyInfoId: Integer read FCompanyInfoId write FCompanyInfoId;
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column]
    property StartDate: NullDate read FStartDate write FStartDate;
    [Column([], 20, 0, 0, 'Firma Tehlike Sýnýfý')]
    property CompanyHazardLevel: NullString read FCompanyHazardLevel write FCompanyHazardLevel;
    [Column([], 50, 0, 0, 'Firma Ýkramiye Dönemleri (, virgülle ayrýlan 1-12 arasý rakamlar)')]
    property BonusPeriods: NullString read FBonusPeriods write FBonusPeriods;
    [Column([], 16, 16, 2, 'Günlük Çalýþma Saati')]
    property WorkHourOfADay: NullExtended read FWorkHourOfADay write FWorkHourOfADay;
    [Column([], 16, 16, 2, 'Bir Ücret Dönemindeki Çalýþma Günleri Sayýsý')]
    property WorkDaysOfAPeriod: NullExtended read FWorkDaysOfAPeriod write FWorkDaysOfAPeriod;

    [Column([], 10, 0, 0, 'Fazla Mesai Tanýmý 1')]
    property OvertimeDef1: NullString read FOvertimeDef1 write FOvertimeDef1;
    [Column([], 16, 16, 2, 'Fazla Mesai 1 yüzdesi')]
    property OvertimeRate1: NullExtended read FOvertimeRate1 write FOvertimeRate1;

    [Column([], 10, 0, 0, 'Fazla Mesai Tanýmý 2')]
    property OvertimeDef2: NullString read FOvertimeDef2 write FOvertimeDef2;
    [Column([], 16, 16, 2, 'Fazla Mesai 2 yüzdesi')]
    property OvertimeRate2: NullExtended read FOvertimeRate2 write FOvertimeRate2;

    [Column([], 10, 0, 0, 'Fazla Mesai Tanýmý 3')]
    property OvertimeDef3: NullString read FOvertimeDef3 write FOvertimeDef3;
    [Column([], 16, 16, 2, 'Fazla Mesai 3 yüzdesi')]
    property OvertimeRate3: NullExtended read FOvertimeRate3 write FOvertimeRate3;
  end;

  [Entity]
  [Table('[EmployeeWage]')]
  TEmployeeWage = class(TBaseModel)
  private
    FEmployeeWageId: Integer;
    FEmployeeId: NullInteger;
    FWageOrBonus: NullInteger;
    FYear: NullInteger;
    FPeriod: NullInteger;
    FAmount: NullExtended;
    FCurrencyId: NullInteger;
    FIsNet: NullBool;
  published
    [Column('EmployeeWageId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property EmployeeWageId: Integer read FEmployeeWageId write FEmployeeWageId;
    [Column]
    [ForeignJoinColumn('EmployeeId', 'Employee', 'EmployeeId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property EmployeeId: NullInteger read FEmployeeId write FEmployeeId;
    [Column([], 0, 0, 0, '0-Gelir mi 1-Gider mi ?')]
    property WageOrBonus: NullInteger read FWageOrBonus write FWageOrBonus;
    [Column]
    property Year: NullInteger read FYear write FYear;
    [Column]
    property Period: NullInteger read FPeriod write FPeriod;
    [Column([], 16, 16, 2, 'Ücret Tutarý')]
    property Amount: NullExtended read FAmount write FAmount;
    [Column]
    [ForeignJoinColumn('CurrencyId', '[Currency]', 'CurrencyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CurrencyId: NullInteger read FCurrencyId write FCurrencyId;
    [Column]
    property IsNet: NullBool read FIsNet write FIsNet;
  end;

  [Entity]
  [Table('[GeneralInfo]')]
  FGeneralInfo = class(TBaseModel)
  private
    FGeneralInfoId: Integer;
    FMinimumWageAmount: NullExtended;
    FStartDate: NullDate;
    FStampDutyRate: NullExtended;
    FIncomeTaxDeduction_1: NullExtended;
    FIncomeTaxDeduction_2: NullExtended;
    FIncomeTaxDeduction_3: NullExtended;
    FIncomeTaxDeduction_4: NullExtended;
    FIncomeTaxDeduction_5: NullExtended;
    FIncomeTaxDeduction_6: NullExtended;
    FIncomeTaxDeduction_7: NullExtended;
    FIncomeTaxDeduction_8: NullExtended;
    FIncomeTaxDeduction_9: NullExtended;
    FIncomeTaxDeduction_10: NullExtended;
  published
    [Column('GeneralInfoId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property GeneralInfoId: Integer read FGeneralInfoId write FGeneralInfoId;
    [Column]
    property StartDate: NullDate read FStartDate write FStartDate;
    [Column([], 16, 16, 2, 'Asgari Ücret Tutarý')]
    property MinimumWageAmount: NullExtended read FMinimumWageAmount write FMinimumWageAmount;
    [Column([], 16, 16, 2, 'Damga Vergisi Oraný')]
    property StampDutyRate: NullExtended read FStampDutyRate write FStampDutyRate;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 1')]
    property IncomeTaxDeduction_1: NullExtended read FIncomeTaxDeduction_1 write FIncomeTaxDeduction_1;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 2')]
    property IncomeTaxDeduction_2: NullExtended read FIncomeTaxDeduction_2 write FIncomeTaxDeduction_2;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 3')]
    property IncomeTaxDeduction_3: NullExtended read FIncomeTaxDeduction_3 write FIncomeTaxDeduction_3;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 4')]
    property IncomeTaxDeduction_4: NullExtended read FIncomeTaxDeduction_4 write FIncomeTaxDeduction_4;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 5')]
    property IncomeTaxDeduction_5: NullExtended read FIncomeTaxDeduction_5 write FIncomeTaxDeduction_5;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 6')]
    property IncomeTaxDeduction_6: NullExtended read FIncomeTaxDeduction_6 write FIncomeTaxDeduction_6;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 7')]
    property IncomeTaxDeduction_7: NullExtended read FIncomeTaxDeduction_7 write FIncomeTaxDeduction_7;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 8')]
    property IncomeTaxDeduction_8: NullExtended read FIncomeTaxDeduction_8 write FIncomeTaxDeduction_8;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 9')]
    property IncomeTaxDeduction_9: NullExtended read FIncomeTaxDeduction_9 write FIncomeTaxDeduction_9;
    [Column([], 16, 16, 2, 'Gelir Vergisi Ýndirimi - 10')]
    property IncomeTaxDeduction_10: NullExtended read FIncomeTaxDeduction_10 write FIncomeTaxDeduction_10;
  end;

  [Entity]
  [Table('[Bank]')]
  TBank = class(TBaseModel)
  private
    FBankId: Integer;
    FCompanyId: NullInteger;
    FBankName: NullString;
    FBankCode: NullString;
  published
    [Column('BankId', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    property BankId: Integer read FBankId write FBankId;
    [Column]
    [ForeignJoinColumn('CompanyId', 'Company', 'CompanyId', [fsOnDeleteSetNull, fsOnUpdateCascade])]
    property CompanyId: NullInteger read FCompanyId write FCompanyId;
    [Column([], 50, 0, 0, 'Banka adý')]
    property BankName: NullString read FBankName write FBankName;
    [Column([], 50, 0, 0, 'Banka kodu')]
    property BankCode: NullString read FBankCode write FBankCode;
  end;



implementation

{ TCity }

function TCity.GetCountryName: string;
begin
  if (FCountry<>nil) and FCountry.CountryName.HasValue then
    Result := FCountry.CountryName
  else
    Result := '';
end;

{ TEmployee }

function TEmployee.GetAdrTownName: string;
begin
  if (FAdrTown<>nil) and FAdrTown.TownName.HasValue then
    Result := FAdrTown.TownName
  else
    Result := '';
end;

function TEmployee.GetCompanyName: string;
begin
  if (FCompany<>nil) and FCompany.CompanyCode.HasValue then
    Result := FCompany.CompanyCode
  else
    Result := '';
end;

function TEmployee.GetNationality: string;
begin
  if (FNationality<>nil) and FNationality.CountryName.HasValue then
    Result := FNationality.CountryName
  else
    Result := '';
end;

function TEmployee.GetTitle: string;
begin
  if (FTitle<>nil) and FTitle.TitleName.HasValue then
    Result := FTitle.TitleName
  else
    Result := '';
end;

{ TTown }

function TTown.GetCity: string;
begin
  if (FCity<>nil) and FCity.CityName.HasValue then
    Result := FCity.CityName
  else
    Result := '';
end;

{ TLocation }

function TLocation.GetTown: string;
begin
  if (FTown<>nil) and FTown.TownName.HasValue then
    Result := FTown.TownName
  else
    Result := '';
end;

{ TDepartment }

function TDepartment.GetCompanyName: string;
begin
  if (FCompany<>nil) and FCompany.CompanyCode.HasValue then
    Result := FCompany.CompanyCode
  else
    Result := '';
end;

function TDepartment.GetTitleName: string;
begin
  if (FTitle<>nil) and FTitle.TitleName.HasValue then
    Result := FTitle.TitleName
  else
    Result := '';

end;

{ TOthIncomeOutcomeDef }

function TOthIncomeOutcomeDef.GetCompanyCode: string;
begin
  if (FCompany<>nil) and FCompany.CompanyCode.HasValue then
    Result := FCompany.CompanyCode
  else
    Result := '';
end;

function TOthIncomeOutcomeDef.GetCompanyName: string;
begin
  if (FCompany<>nil) and FCompany.CompanyName1.HasValue then
    Result := FCompany.CompanyName1
  else
    Result := '';
end;

function TOthIncomeOutcomeDef.GetComputationTypeText: string;
var sl : TStringList;
begin
  sl := TStringList.Create;
  try
    Result := '';
    sl.Text := ComponentListDictionary.GetText(ClassName, 'ComputationType.Items.Text');
    if sl.Count<>0 then
      case ComputationType of
      Amount : Result := sl[0];
      Percentage : Result := sl[1];
      ComputeWithScript : Result := sl[2];
      end;
  finally
    sl.Free;
  end;
end;

function TOthIncomeOutcomeDef.GetCurrencyCode: string;
begin
  if (FCurrency<>nil) and FCurrency.CurrencyCode.HasValue then
    Result := FCurrency.CurrencyCode
  else
    Result := '';
end;

function TOthIncomeOutcomeDef.GetCurrencyName: string;
begin
  if (FCurrency<>nil) and FCurrency.CurrencyName.HasValue then
    Result := FCurrency.CurrencyName
  else
    Result := '';
end;

function TOthIncomeOutcomeDef.GetIncomeOutcomeText: string;
var sl : TStringList;
begin
  Result := '';
  if not(IncomeOutcome.HasValue) then
    Exit;
  sl := TStringList.Create;
  try
    sl.Text := ComponentListDictionary.GetText(ClassName, 'IncomeOutcome.Items.Text');
    if sl.Count<>0 then
      case IncomeOutcome.Value of
      0 : Result := sl[0];
      1 : Result := sl[1];
      end;
  finally
    sl.Free;
  end;
end;

{ TUser }

function TUser.GetCompanyCode: string;
begin
  if (FCompany<>nil) and FCompany.CompanyCode.HasValue then
    Result := FCompany.CompanyCode
  else
    Result := '';
end;

function TUser.GetCompanyName: string;
begin
  if (FCompany<>nil) and FCompany.CompanyName1.HasValue then
    Result := FCompany.CompanyName1
  else
    Result := '';
end;

function TUser.GetLocationCode: string;
begin
  if (FLocation<>nil) and FLocation.LocationCode.HasValue then
    Result := FLocation.LocationCode
  else
    Result := '';
end;

function TUser.GetLocationName: string;
begin
  if (FLocation<>nil) and FLocation.LocationName.HasValue then
    Result := FLocation.LocationName
  else
    Result := '';
end;

{ TCompanyLocation

function TCompanyLocation.GetLocationCode: string;
begin
  if (FLocation<>nil) and FLocation.LocationCode.HasValue then
    Result := FLocation.LocationCode
  else
    Result := '';
end;

function TCompanyLocation.GetLocationName: string;
begin
  if (FLocation<>nil) and FLocation.LocationName.HasValue then
    Result := FLocation.LocationName
  else
    Result := '';
end;}

{ TGroupUserExt }

function TGroupUserExt.GetGroupName: string;
begin
  {if (FGroup<>nil) and FGroup.GroupName.HasValue then
    Result := FGroup.GroupName
  else
    Result := '';}
  Result := FGroupName;
end;

function TGroupUserExt.GetUsername: string;
begin
  {if (FUser<>nil) and FUser.Username.HasValue then
    Result := FUser.Username
  else
    Result := '';}
  Result := FUsername;
end;

procedure TGroupUserExt.SetGroupName(const Value: string);
begin
  FGroupName := Value;
end;

procedure TGroupUserExt.SetUserName(const Value: string);
begin
  FUserName := Value;
end;

{ TRole }

function TRole.GetCompanyCode: string;
begin
  if (FCompany<>nil) and FCompany.CompanyCode.HasValue then
    Result := FCompany.CompanyCode
  else
    Result := '';
end;

function TRole.GetCompanyName: string;
begin
  if (FCompany<>nil) and FCompany.CompanyName1.HasValue then
    Result := FCompany.CompanyName1
  else
    Result := '';
end;

end.
